workflow: smartspim

# Base working directory where images of all channels reside
workdir: /mnt/beegfs/joha/scripts/pacqproc/datasets/toy

channels:
  - Ex_0_Em_0
  - Ex_1_Em_1

labels:
  - ch0
  - ch1

processes:
  - destripe
  - stitch
  - precomputed

filetype: raw

# Index of master channel for stitching (0-based).
# Remaining channels will be stitched based on 
# the calculation obtained from the master channel.
master_channel_index: 1

# Voxel sizes in µm (x, y, z)
voxel_size: 0.66,0.66,2.0

# Tiff output compression level
compression: 4

# Maximum # of threads to be employed
threads: 32

# Paths to `terastitcher` binary and `mpstitcher.py` Python script
terastitcher: /mnt/beegfs/joha/scripts/pacqproc/bin/terastitcher
mpstitcher: /mnt/beegfs/joha/scripts/pacqproc/bin/mpstitcher.py